version: '3.8'

services:
  frontend:
    container_name: amore-frontend
    build:
      context: ./front-form
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DEBUG=true
      - NEXT_TELEMETRY_DEBUG=1
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NEXT_PUBLIC_CLIENT_API_URL=http://localhost:8000
    depends_on:
      - backend

  backend:
    container_name: amore-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/amore_db
    depends_on:
      - db

  db:
    container_name: amore-postgres
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=amore_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 